language: python
python:
  - "3.3"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - "pylint --rcfile=.pylintrc *.py -f parseable -r n && \
  pycodestyle *.py --max-line-length=120 && \
  pydocstyle *.py && \
  py.test --doctest-modules --cov=*.py --cov-report term-missing"
branches:
  only:
    - master
after_success:
  - coveralls
