language: python
python:
  - "3.2"
  - "3.3"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - py.test --doctest-modules --cov=hello_world --cov-report term-missing
branches:
  only:
    - master
