language: python
python:
  - "3.3"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pylint "--rcfile=.pylintrc hello_world -f parseable -r n && \
  pycodestyle hello_world.py --max-line-length=120 && \
  pydocstyle hello_world.py && \
  py.test --doctest-modules --cov=hello_world --cov-report term-missing"
branches:
  only:
    - master
after_success:
  - coveralls
